### ISSUE TITLE
watching fs?

### ISSUE THREAD

**Issue by ScottFreeCode** [andrewrk/connect-static#8]
Does this support watching the filesystem for new files added to the directory and/or changes to files that are being statically served? If not, would an update be considered to add that as an option or to make it possible for the user to plug in their own code that implements it?

**Comment by rkaw92** [comment]
Hi,
we've had a similar use case, but with "manual" reloads when a signal is delivered. We settled for zero-downtime reloads by generating a new connect-static instance and atomically replacing the entire HTTP request handler every time. Hope that helps.

**Comment by andrewrk** [comment]
I'm optimizing for a simple use case here, and watching the fs is out of scope for this project. You can consider using `serve-static` or look into making something more complicated.
